name: Auto release PR

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: write # to create release
  pull-requests: write # to create release PR

jobs:
  # from https://github.com/peter-evans/create-pull-request/blob/main/docs/examples.md#keep-a-branch-up-to-date-with-another
  productionRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: production
      - name: Fetch all tags
        run: git fetch --tags
      - name: Get latest tag
        id: get_latest_tag
        run: echo "tag=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_OUTPUT
      - name: Checkout latest tag
        run: git checkout ${{ steps.get_latest_tag.outputs.tag }}
      - name: Force update production branch to latest tag
        run: |
          git checkout production
          git reset --hard ${{ steps.get_latest_tag.outputs.tag }}
          git push origin production --force
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7.0.5
        with:
          branch: production-release
          title: 'chore: Point production to release ${{ steps.get_latest_tag.outputs.tag }}'
          body: 'This PR points the production branch to release ${{ steps.get_latest_tag.outputs.tag }}.'

  stagingRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: staging
      - name: Fetch all tags
        run: git fetch --tags
      - name: Get latest tag
        id: get_latest_tag
        run: echo "tag=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_OUTPUT
      - name: Checkout latest tag
        run: git checkout ${{ steps.get_latest_tag.outputs.tag }}
      - name: Force update staging branch to latest tag
        run: |
          git checkout staging
          git reset --hard ${{ steps.get_latest_tag.outputs.tag }}
          git push origin staging --force
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7.0.5
        with:
          branch: staging-release
          title: 'chore: point staging to release ${{ steps.get_latest_tag.outputs.tag }}'
          body: 'This PR points the staging branch to release ${{ steps.get_latest_tag.outputs.tag }}.'
